development:
  adapter: postgresql
  encoding: utf8
  database: beer
  pool: 5
  username: beer
  password: '!beer4you'

test: &test
  adapter: postgresql
  encoding: utf8
  database: beer_test
  pool: 5
  username: beer
  password: '!beer4you'

production:
  adapter: postgresql
  encoding: utf8
  database: beer
  pool: 5
  username: beer
  password: '!beer4you'

cucumber:
  <<: *test
