development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: kassa_development
  pool:     5
  username: <%= Rails.application.secrets.postgres_user %>
  password: <%= Rails.application.secrets.postgres_password %>

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: kassa_test
  pool:     5
  username: <%= Rails.application.secrets.postgres_user %>
  password: <%= Rails.application.secrets.postgres_password %>

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: kassa_production
  pool:     5
  username: <%= Rails.application.secrets.postgres_user %>
  password: <%= Rails.application.secrets.postgres_password %>
